In [87]:
import pandas as pd

In [88]:
import numpy as np

In [89]:
df = pd.read_csv('../../data/datasets/dataset_1_3.csv', sep=';', encoding='utf-8-sig', low_memory=False)

In [90]:
df.head()

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Город законченного уч. зав.,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2
1,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p9a199s0tmd01fs,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Архитектура ЭВМ_3
2,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p9a1uimadbqc25o,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Анализ данных и искусственный интеллект_3
3,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p91r12floo1c7uc,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Прикладная физическая культура_3
4,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqc4snbpauvougo,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Прикладная физическая культура_1

In [91]:
df_1_sem = df[df["Сквозной семестр"] < 3]
df_1_sem = df_1_sem[df_1_sem["Год начала обучения"] == 2023]

In [92]:
df_1_sem.head()

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Город законченного уч. зав.,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2
4,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqc4snbpauvougo,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Прикладная физическая культура_1
6,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqib6f365d55omc,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1
7,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0okbqkb7dg8u54,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Философия_2
8,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,NaN,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000os603jlf5koit64,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1

In [93]:
df_1_sem['Балл за инд. достижения'] = df_1_sem['Балл за инд. достижения'].fillna(0)

In [94]:
df_1_sem.isna().sum()

UUID студента                            0
Приоритет                                0
Cумма баллов испытаний                   0
БВИ                                      0
Балл за инд. достижения                  0
                                     ...
Квалификация зак.уч.зав.             36866
Специальность зак.уч.зав.            34742
Льготы                               44808
Документы подтв. льготы              44998
Наименование дисциплины + семестр        0
Length: 67, dtype: int64

In [95]:
df_1_sem["Новый таргет"] = df_1_sem["Состояние студента"]

In [96]:
df_1_sem.head()

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2,Активный
4,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqc4snbpauvougo,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Прикладная физическая культура_1,Активный
6,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqib6f365d55omc,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1,Активный
7,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0okbqkb7dg8u54,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Философия_2,Активный
8,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000os603jlf5koit64,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1,Активный

In [97]:
# Сначала создаём маску с правильными условиями
mask = (
    ((df_1_sem["Курс"] != 1) & 
    (df_1_sem["Состояние студента"] != "Активный")) |
    ((df_1_sem["Сквозной семестр"] != 1) & 
    (df_1_sem["Состояние студента"] != "Активный"))
)

# Затем обновляем значения для строк, соответствующих маске
df_1_sem.loc[mask, "Новый таргет"] = "Активный"

In [98]:
df_1_sem["Новый таргет"].head()

0    Активный
4    Активный
6    Активный
7    Активный
8    Активный
Name: Новый таргет, dtype: object

In [99]:
# Выбираем строки, где "Состояние студента" != "новый таргет"
changed_rows = df_1_sem[df_1_sem["Состояние студента"] != df_1_sem["Новый таргет"]]

# Выводим результат (можно добавить фильтр по нужным столбцам)
changed_rows[["UUID студента", "Состояние студента", "Новый таргет", "Курс", "Сквозной семестр"]]

,UUID студента,Состояние студента,Новый таргет,Курс,Сквозной семестр
368,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
373,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
374,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
376,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
377,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
...,...,...,...,...,...
61271,studen195e3pg0000ok208bl08bh35t4,Отчислен,Активный,1,2
61272,studen195e3pg0000ok208bl08bh35t4,Отчислен,Активный,1,2
61274,studen195e3pg0000ok208bl08bh35t4,Отчислен,Активный,1,2
61276,studen195e3pg0000ok208bl08bh35t4,Отчислен,Активный,1,2
61277,studen195e3pg0000ok208bl08bh35t4,Отчислен,Активный,1,2

In [100]:
changed_rows[["UUID студента", "Состояние студента", "Новый таргет", "Курс", "Сквозной семестр"]].head(30)

,UUID студента,Состояние студента,Новый таргет,Курс,Сквозной семестр
368,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
373,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
374,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
376,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
377,studen195e3pg0000ok202gfub3pbmj4,Отчислен,Активный,1,2
540,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
541,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
544,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
545,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
546,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
550,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
553,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
554,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
555,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
560,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
561,studen195e3pg0000ok21ho0mk63onnk,Отчислен,Активный,1,2
714,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
715,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
717,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
722,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
723,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
724,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
727,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
728,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
731,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
732,studen195e3pg0000ok20h7lid3nit9k,Отчислен,Активный,1,2
734,studen195e3pg0000ok2328o67lpdh38,Отчислен,Активный,2,2
735,studen195e3pg0000ok2328o67lpdh38,Отчислен,Активный,2,1
736,studen195e3pg0000ok2328o67lpdh38,Отчислен,Активный,2,2
737,studen195e3pg0000ok2328o67lpdh38,Отчислен,Активный,2,2

In [101]:
df_1_sem = df_1_sem.drop("Состояние студента", axis=1)

In [102]:
df_1_sem.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0.0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2,Активный

In [103]:
df_1_sem["Балл за инд. достижения"].unique()

array([ 0.,  3.,  2.,  5.,  6., 10.,  7.,  9.,  4.,  8.,  1.])

In [104]:
df_1_sem["Балл за инд. достижения"] = df_1_sem["Балл за инд. достижения"].astype(int)

In [105]:
df_1_sem.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2,Активный

In [106]:
df_1_sem["Вид конкурса"].unique()

array(['Особая квота', 'Целевая квота', 'Отдельная квота',
       'Основные места'], dtype=object)

In [107]:
benefit = df_1_sem["Льготы"].unique()

In [108]:
benefit

array(['02 Лица из числа детей-сирот (до 23 лет)', nan,
       '04 Дети-инвалиды',
       '05 Лица из числа детей без попечения родителей (до 23 лет)',
       '21 Дети военнослужащих, погибших или получивших увечье при исполнении обязанностей военной службы в специальной военной операции на территориях Украины',
       '07 Инвалиды с детства',
       '19 Дети лиц, принимавших участие в специальной военной операции на территориях Украины',
       '17 Дети военнослужащих, сотрудников федеральных органов исполнительной власти и федеральных государственных органов, направленных в другие государства',
       '11 Инвалиды II группы', '10 Ветераны боевых действий',
       '03 Дети, оставшиеся без попечения родителей (до 18 лет)',
       '09 Лица, поступающие по направлению Министерства в пределах квоты, установленной Правительством Российской Федерации'],
      dtype=object)

In [109]:
df_1_sem["Категория конкурса БВИ"].unique()

array([nan,
       '21 Дети военнослужащих, погибших или получивших увечье при исполнении обязанностей военной службы в специальной военной операции на территориях Украины',
       '2020:  Всероссийская олимпиада школьников',
       '62 Открытая олимпиада школьников',
       '26 Международная олимпиада школьников Уральского федерального университета "Изумруд"',
       '09 Лица, поступающие по направлению Министерства в пределах квоты, установленной Правительством Российской Федерации',
       '2022: 25 Международная олимпиада школьников Уральского федерального университета "Изумруд"',
       '64 Открытая олимпиада школьников по программированию "Когнитивные технологии"',
       '2022: 37 Многопрофильная инженерная олимпиада "Звезда"',
       '36 Многопрофильная инженерная олимпиада "Звезда"',
       '67 Отраслевая олимпиада школьников "Газпром"',
       '79 Университетская олимпиада школьников "Бельчонок"',
       '2022: 15 Вузовско-академическая олимпиада по информатике',
       '47 Олимпиада школьников "Гранит науки"',
       '2020: 35 Многопрофильная олимпиада школьников Уральского федерального университета «Изумруд»',
       '15 Вузовско-академическая олимпиада по информатике',
       'Лица, поступающие по направлению Министерства в пределах квоты, установленной Правительством Российской Федерации'],
      dtype=object)

In [110]:
df_1_sem.loc[df_1_sem["Категория конкурса БВИ"].isin(benefit), "Категория конкурса БВИ"] = np.nan

In [111]:
# Выводим строки, где "Категория конкурса БВИ" стала NaN
df_1_sem[df_1_sem["Категория конкурса БВИ"].isna()].head()

# Или проверяем количество изменений:
# print("Число замененных строк:", df_1_sem["Категория конкурса БВИ"].isna().sum())

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0ojcks1r0brulk,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2,Активный
4,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqc4snbpauvougo,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Прикладная физическая культура_1,Активный
6,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000oqib6f365d55omc,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1,Активный
7,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000p0okbqkb7dg8u54,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Философия_2,Активный
8,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,NaN,qldflt195e3pg0000os603jlf5koit64,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Математика_1,Активный

In [112]:
df_1_sem[df_1_sem["UUID студента"] == "studen195e3pg0000ok210qds16h2lps"].head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
281,studen195e3pg0000ok210qds16h2lps,1,0,1,0,Отдельная квота,NaN,NaN,NaN,qldflt195e3pg0000p4j535qjr0kade4,...,Средняя общеобразовательная школа,Средняя общеобразовательная школа Муниципально...,2023,Аттестат о среднем общем образовании,NaN,NaN,"21 Дети военнослужащих, погибших или получивши...","Документ, подтверждающий принадлежность к детя...",Дифференциальные уравнения и численные методы_2,Активный

In [113]:
df_1_sem["Категория конкурса БВИ"].unique()

array([nan, '2020:  Всероссийская олимпиада школьников',
       '62 Открытая олимпиада школьников',
       '26 Международная олимпиада школьников Уральского федерального университета "Изумруд"',
       '2022: 25 Международная олимпиада школьников Уральского федерального университета "Изумруд"',
       '64 Открытая олимпиада школьников по программированию "Когнитивные технологии"',
       '2022: 37 Многопрофильная инженерная олимпиада "Звезда"',
       '36 Многопрофильная инженерная олимпиада "Звезда"',
       '67 Отраслевая олимпиада школьников "Газпром"',
       '79 Университетская олимпиада школьников "Бельчонок"',
       '2022: 15 Вузовско-академическая олимпиада по информатике',
       '47 Олимпиада школьников "Гранит науки"',
       '2020: 35 Многопрофильная олимпиада школьников Уральского федерального университета «Изумруд»',
       '15 Вузовско-академическая олимпиада по информатике',
       'Лица, поступающие по направлению Министерства в пределах квоты, установленной Правительством Российской Федерации'],
      dtype=object)

In [114]:
benefit

array(['02 Лица из числа детей-сирот (до 23 лет)', nan,
       '04 Дети-инвалиды',
       '05 Лица из числа детей без попечения родителей (до 23 лет)',
       '21 Дети военнослужащих, погибших или получивших увечье при исполнении обязанностей военной службы в специальной военной операции на территориях Украины',
       '07 Инвалиды с детства',
       '19 Дети лиц, принимавших участие в специальной военной операции на территориях Украины',
       '17 Дети военнослужащих, сотрудников федеральных органов исполнительной власти и федеральных государственных органов, направленных в другие государства',
       '11 Инвалиды II группы', '10 Ветераны боевых действий',
       '03 Дети, оставшиеся без попечения родителей (до 18 лет)',
       '09 Лица, поступающие по направлению Министерства в пределах квоты, установленной Правительством Российской Федерации'],
      dtype=object)

In [115]:
df_1_sem['Категория конкурса БВИ'] = np.where(df_1_sem['Категория конкурса БВИ'].notna(), '1', "0")

In [116]:
df_1_sem['Категория конкурса БВИ'].unique()

array(['0', '1'], dtype=object)

In [117]:
df_1_sem['Категория конкурса БВИ']

0        0
4        0
6        0
7        0
8        0
        ..
68486    1
68487    1
68488    1
68489    1
68493    1
Name: Категория конкурса БВИ, Length: 46421, dtype: object

In [118]:
df_1_sem['Категория конкурса БВИ'] = df_1_sem['Категория конкурса БВИ'].astype(int)

In [119]:
# df_1_sem["Льготы"] = np.where(df_1_sem["Льготы"].notna(), '1', "0")

In [120]:
# df_1_sem["Льготы"] = df_1_sem['Льготы'].astype(int)

In [121]:
df_1_sem.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Наименование олимпиады,Тип олимпиады,Категория конкурса БВИ,UUID оценки,...,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Наименование дисциплины + семестр,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,NaN,0,qldflt195e3pg0000p0ojcks1r0brulk,...,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Проектный практикум 1_2,Активный

In [122]:
df_1_sem = df_1_sem.drop("Наименование олимпиады", axis=1)

In [123]:
df_1_sem = df_1_sem.drop("UUID оценки", axis=1)

In [124]:
columns_lst = df_1_sem.columns

In [125]:
print(*columns_lst.to_list(), sep='\n')

UUID студента
Приоритет
Cумма баллов испытаний
БВИ
Балл за инд. достижения
Вид конкурса
Тип олимпиады
Категория конкурса БВИ
Контрольное мероприятие
Тип оценки
Наименование дисциплины
Модель реализации
Оценка
Балл
Дата получения оценки
Семестр
Сквозной семестр
Год
Наименование дисциплины ИТС
ИТС наименование в дипломе
Код направления подготовки
Наименование напр. подготовки
Образовательная программа
ЛН студента
ЛН студента (архив)
Основа освоения (сокр.)
Форма освоения
Формирующее подразделение
Год начала обучения
Срок освоения
Уровень подготовки
Область образования
Целевик
Хоз. группа | Вкл. обучение
Нуждается в общежитии
Малоимущий
Слушатель
Иностранный абитуриент (МОН)
Курс
Активное состояние
В архиве
Приказ об отчислении
Акад. отп. по сост. здор.
Акад. отп. по уходу за реб.
UUID персоны
Пол
Дата рождения
Место рождения
Гражданство
Адрес регистрации. Страна
Адрес регистрации. Область
Адрес регистрации. Город
Страна законченного уч. зав.
Регион законченного уч. зав.
Город законченного уч. зав.
Тип законченного уч. зав.
Название законченного уч. зав.
Год окончание уч. зав.
Тип документа об образовании
Квалификация зак.уч.зав.
Специальность зак.уч.зав.
Льготы
Документы подтв. льготы
Наименование дисциплины + семестр
Новый таргет

In [126]:
columns_to_drop = ["Контрольное мероприятие", "Тип оценки", "Наименование дисциплины", "Модель реализации", "Оценка", "Балл",
                   "Дата получения оценки", "Семестр", "Сквозной семестр", "Год", "Наименование дисциплины ИТС", "ИТС наименование в дипломе",
                   "Год начала обучения", "Курс", "Активное состояние", "Место рождения", "Наименование дисциплины + семестр"]

df_1_sem_1 = df_1_sem.drop(columns=columns_to_drop)

In [127]:
df_1_sem_1.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Тип олимпиады,Категория конкурса БВИ,Код направления подготовки,Наименование напр. подготовки,...,Город законченного уч. зав.,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,0,09.03.04,Программная инженерия,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Активный

In [128]:
# df_1_sem = df_1_sem.drop("UUID оценки", axis=1)
df_1_sem_1["Код направления подготовки"].nunique()

20

In [129]:
df_1_sem_1["Образовательная программа"].nunique()

27

In [130]:
lst1 = df_1_sem_1["Наименование напр. подготовки"].unique().tolist()
lst2 = df_1_sem_1["Образовательная программа"].unique().tolist()

# for val in lst1:
#     lst2.remove(val)
lst1.sort()
lst2.sort()

print(lst1)
print(lst2)

['Инфокоммуникационные технологии и системы связи', 'Информатика и вычислительная техника', 'Информационная безопасность', 'Информационная безопасность телекоммуникационных систем', 'Информационно-аналитические системы безопасности', 'Информационные системы и технологии', 'Конструирование и технология электронных средств', 'Прикладная информатика', 'Программная инженерия', 'Радиотехника', 'Радиоэлектронные системы и комплексы', 'Технология полиграфического и упаковочного производства', 'Управление в технических системах']
['IT инновации в бизнесе', 'Алгоритмы искусственного интеллекта', 'Безопасность компьютерных систем', 'Защита информации в информационных системах персональных данных, государственных информационных системах и значимых объектах критической информационной инфраструктуры', 'Инженерия искусственного интеллекта', 'Инженерия машинного обучения', 'Инженерия радиоэлектронных средств и систем', 'Интеллектуальные информационные системы и технологии в медицине', 'Инфокоммуникационные технологии и системы связи', 'Информатика и вычислительная техника', 'Информационная безопасность телекоммуникационных систем', 'Информационно-аналитические системы безопасности', 'Информационно-управляющие системы', 'Конструирование и технология электронных средств', 'Прикладная информатика', 'Прикладной анализ данных', 'Прикладной искусственный интеллект', 'Программная инженерия', 'Промышленные графические системы и цифровые фототехнологии', 'Радиотехника', 'Радиоэлектронные системы и комплексы', 'Разработка и управление в программных проектах', 'Разработка программно-информационных систем', 'Системы управления сложными объектами и процессами', 'Технология полиграфического и упаковочного производства', 'Управление в технических системах', 'Электроника, радиотехника и системы связи']

In [131]:
sorted_list = sorted(df_1_sem_1["Код направления подготовки"].unique().tolist())
sorted_list

['09.03.01',
 '09.03.03',
 '09.03.04',
 '09.04.01',
 '09.04.02',
 '09.04.03',
 '09.04.04',
 '10.03.01',
 '10.04.01',
 '10.05.02',
 '10.05.04',
 '11.03.01',
 '11.03.02',
 '11.03.03',
 '11.04.01',
 '11.05.01',
 '27.03.04',
 '27.04.04',
 '29.03.03',
 '29.04.03']

In [132]:
df_1_sem_1.columns

Index(['UUID студента', 'Приоритет', 'Cумма баллов испытаний', 'БВИ',
       'Балл за инд. достижения', 'Вид конкурса', 'Тип олимпиады',
       'Категория конкурса БВИ', 'Код направления подготовки',
       'Наименование напр. подготовки', 'Образовательная программа',
       'ЛН студента', 'ЛН студента (архив)', 'Основа освоения (сокр.)',
       'Форма освоения', 'Формирующее подразделение', 'Срок освоения',
       'Уровень подготовки', 'Область образования', 'Целевик',
       'Хоз. группа | Вкл. обучение', 'Нуждается в общежитии', 'Малоимущий',
       'Слушатель', 'Иностранный абитуриент (МОН)', 'В архиве',
       'Приказ об отчислении', 'Акад. отп. по сост. здор.',
       'Акад. отп. по уходу за реб.', 'UUID персоны', 'Пол', 'Дата рождения',
       'Гражданство', 'Адрес регистрации. Страна',
       'Адрес регистрации. Область', 'Адрес регистрации. Город',
       'Страна законченного уч. зав.', 'Регион законченного уч. зав.',
       'Город законченного уч. зав.', 'Тип законченного уч. зав.',
       'Название законченного уч. зав.', 'Год окончание уч. зав.',
       'Тип документа об образовании', 'Квалификация зак.уч.зав.',
       'Специальность зак.уч.зав.', 'Льготы', 'Документы подтв. льготы',
       'Новый таргет'],
      dtype='object')

In [133]:
lst1 = df_1_sem_1["Наименование напр. подготовки"].to_list()
lst2 = df_1_sem_1["Наименование напр. подготовки"].to_list()

In [134]:
df_1_sem_1.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Тип олимпиады,Категория конкурса БВИ,Код направления подготовки,Наименование напр. подготовки,...,Город законченного уч. зав.,Тип законченного уч. зав.,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Новый таргет
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,0,09.03.04,Программная инженерия,...,не указано,Колледж,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Активный

In [159]:
df_1_sem_2 = df_1_sem_1.drop_duplicates(subset=['UUID студента'], keep='first')

In [160]:
df_1_sem_2.shape

(2281, 50)

In [193]:
df_1_sem_2["Код направления 1"] = np.nan
df_1_sem_2["Код направления 3"] = np.nan


df_1_sem_2[["Код направления 1", "Код направления 3"]] = df_1_sem_2["Код направления подготовки"].apply(
    lambda x: pd.Series({
        "Код направления 1": int(x.split(".")[0]),
        "Код направления 3": int(x.split(".")[2])
    })
)

In [191]:
df_1_sem_2["Часть1"].unique()

array([ 9, 11, 10, 27, 29])

In [200]:
df_1_sem_2.head(1)

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Тип олимпиады,Категория конкурса БВИ,Основа освоения (сокр.),Форма освоения,...,Название законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Квалификация зак.уч.зав.,Специальность зак.уч.зав.,Льготы,Документы подтв. льготы,Новый таргет,Код направления 1,Код направления 3
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,0,бюджет,Очная,...,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕПРОФЕССИОНАЛЬНОЕОБРАЗ...,2023,Диплом о среднем профессиональном образовании,NaN,NaN,02 Лица из числа детей-сирот (до 23 лет),31 Копия свидетельства о смерти матери,Активный,9,4

In [196]:
df_1_sem_2 = df_1_sem_2.drop(columns=["Код направления подготовки", "Наименование напр. подготовки", "Образовательная программа"])

In [199]:
df_1_sem_2 = df_1_sem_2.drop(columns=["ЛН студента", "ЛН студента (архив)"])

In [201]:
df_1_sem_2["Основа освоения (сокр.)"].unique()

array(['бюджет', 'контракт'], dtype=object)

In [202]:
df_1_sem_2.columns

Index(['UUID студента', 'Приоритет', 'Cумма баллов испытаний', 'БВИ',
       'Балл за инд. достижения', 'Вид конкурса', 'Тип олимпиады',
       'Категория конкурса БВИ', 'Основа освоения (сокр.)', 'Форма освоения',
       'Формирующее подразделение', 'Срок освоения', 'Уровень подготовки',
       'Область образования', 'Целевик', 'Хоз. группа | Вкл. обучение',
       'Нуждается в общежитии', 'Малоимущий', 'Слушатель',
       'Иностранный абитуриент (МОН)', 'В архиве', 'Приказ об отчислении',
       'Акад. отп. по сост. здор.', 'Акад. отп. по уходу за реб.',
       'UUID персоны', 'Пол', 'Дата рождения', 'Гражданство',
       'Адрес регистрации. Страна', 'Адрес регистрации. Область',
       'Адрес регистрации. Город', 'Страна законченного уч. зав.',
       'Регион законченного уч. зав.', 'Город законченного уч. зав.',
       'Тип законченного уч. зав.', 'Название законченного уч. зав.',
       'Год окончание уч. зав.', 'Тип документа об образовании',
       'Квалификация зак.уч.зав.', 'Специальность зак.уч.зав.', 'Льготы',
       'Документы подтв. льготы', 'Новый таргет', 'Код направления 1',
       'Код направления 3'],
      dtype='object')

In [208]:
df_1_sem_2["Регион законченного уч. зав."].isna().sum()

np.int64(1278)

In [209]:
col_to_drop = ["Формирующее подразделение", "Область образования", "Целевик", "Хоз. группа | Вкл. обучение", 
               "Малоимущий", "Слушатель", "В архиве", "Приказ об отчислении", "Акад. отп. по сост. здор.", "Акад. отп. по уходу за реб.", 
               "UUID персоны", "Адрес регистрации. Страна", "Адрес регистрации. Область", "Адрес регистрации. Город", "Страна законченного уч. зав.",
               "Название законченного уч. зав.", "Регион законченного уч. зав.", "Квалификация зак.уч.зав.", "Специальность зак.уч.зав.", "Документы подтв. льготы"]

current_col = df_1_sem_2.columns.tolist()
for col in col_to_drop:
    if col not in current_col:
        print(col)

In [211]:
df_1_sem_2 = df_1_sem_2.drop(columns=col_to_drop)

In [213]:
df_1_sem_2.head()

,UUID студента,Приоритет,Cумма баллов испытаний,БВИ,Балл за инд. достижения,Вид конкурса,Тип олимпиады,Категория конкурса БВИ,Основа освоения (сокр.),Форма освоения,...,Дата рождения,Гражданство,Город законченного уч. зав.,Тип законченного уч. зав.,Год окончание уч. зав.,Тип документа об образовании,Льготы,Новый таргет,Код направления 1,Код направления 3
0,studen195e3pg0000ok22fnqsr14o7ek,1,205,0,0,Особая квота,NaN,0,бюджет,Очная,...,19.10.2002,Российская Федерация,не указано,Колледж,2023,Диплом о среднем профессиональном образовании,02 Лица из числа детей-сирот (до 23 лет),Активный,9,4
28,studen195e3pg0000ok226fn6ou3b2v0,5,236,0,0,Целевая квота,NaN,0,бюджет,Очная,...,09.07.2005,Российская Федерация,Серов,Техникум,2023,Аттестат о среднем общем образовании,NaN,Активный,9,4
56,studen195e3pg0000ok22cs2kmm1iuds,1,154,0,0,Целевая квота,NaN,0,бюджет,Очная,...,03.02.2005,Российская Федерация,Чусовой,Средняя общеобразовательная школа,2023,Аттестат о среднем общем образовании,NaN,Активный,9,4
85,studen195e3pg0000ok229rk4q8f5ru4,1,209,0,3,Особая квота,NaN,0,бюджет,Очная,...,26.12.2005,Российская Федерация,Пышма,Средняя общеобразовательная школа,2023,Аттестат о среднем общем образовании,04 Дети-инвалиды,Активный,9,4
115,studen195e3pg0000ok22a5a0pqm86ag,1,196,0,0,Особая квота,NaN,0,бюджет,Очная,...,17.10.2005,Российская Федерация,не указано,Средняя общеобразовательная школа,2023,Аттестат о полном среднем образовании,05 Лица из числа детей без попечения родителей...,Активный,9,4

In [214]:
df_1_sem_2.to_csv('../../data/datasets/dataset_1sem_4.csv', sep=';', index=False, encoding='utf-8-sig')